
const authTypes = {
    SET_REDIR: 'SET_REDIR',
    RES_LOGIN: 'RES_LOGIN',
    REQ_LOGIN: 'REQ_LOGIN',
    REQ_REGISTER: 'REQ_REGISTER',
    RES_REGISTER: 'RES_REGISTER',
    ERR_REGISTER: 'ERR_REGISTER',
    LOGOUT: 'LOGOUT',
};

const artefactTypes = {
    RES_GET_BROWSER_ARTEFACTS: 'RES_GET_BROWSER_ARTEFACTS',
    REQ_GET_BROWSER_ARTEFACTS: 'REQ_GET_BROWSER_ARTEFACTS',
    ERR_GET_BROWSER_ARTEFACTS: 'ERR_GET_BROWSER_ARTEFACTS',


    REQ_GET_MY_ARTEFACTS: 'REQ_GET_MY_ARTEFACTS',
    RES_GET_MY_ARTEFACTS: 'RES_GET_MY_ARTEFACTS',
    ERR_GET_MY_ARTEFACTS: 'ERR_GET_MY_ARTEFACTS',

    ADD_MY_ARTEFACTS: 'ADD_MY_ARTEFACTS',
    RES_CREATE_MY_ARTEFACTS: 'RES_CREATE_MY_ARTEFACTS',
    REQ_CREATE_MY_ARTEFACTS: 'REQ_CREATE_MY_ARTEFACTS',

    REQ_GET_ARTEFACT: 'REQ_GET_ARTEFACT',
    RES_GET_ARTEFACT: 'RES_GET_ARTEFACT',
    ERR_GET_ARTEFACT: 'ERR_GET_ARTEFACT',

    SET_PUBLIC_ARTEFACTS: 'SET_PUBLIC_ARTEFACTS',
    REQ_GET_PUBLIC_ARTEFACTS: 'REQ_GET_PUBLIC_ARTEFACTS',
    RES_GET_PUBLIC_ARTEFACTS: 'RES_GET_PUBLIC_ARTEFACTS',
    ERR_GET_PUBLIC_ARTEFACTS: 'ERR_GET_PUBLIC_ARTEFACTS',

    REQ_GET_USER_ARTEFACTS: 'REQ_GET_USER_ARTEFACTS',
    RES_GET_USER_ARTEFACTS: 'RES_GET_USER_ARTEFACTS',
    ERR_GET_USER_ARTEFACTS: 'ERR_GET_USER_ARTEFACTS',
};

// artefacts of a specific user
const usersTypes = {
    REQ_GET_USER: 'REQ_GET_USER',
    RES_GET_USER: 'RES_GET_USER',
    ERR_GET_USER: 'ERR_GET_USER',

    REQ_PATCH_USER_DETAILS: 'REQ_PATCH_USER_DETAILS',
    RES_PATCH_USER_DETAILS: 'RES_PATCH_USER_DETAILS',
    ERR_PATCH_USER_DETAILS: 'ERR_PATCH_USER_DETAILS',
};

const discussTypes = {
    REQ_GET_DISCUSSION: 'REQ_GET_DISCUSSION',
    RES_GET_DISCUSSION: 'RES_GET_DISCUSSION',
    ERR_GET_DISCUSSION: 'ERR_GET_DISCUSSION',

    REQ_POST_DISCUSSION: 'REQ_POST_DISCUSSION',
    RES_POST_DISCUSSION: 'RES_POST_DISCUSSION',
    ERR_POST_DISCUSSION: 'ERR_POST_DISCUSSION',
};

export {
    authTypes,
    artefactTypes,
    usersTypes,
    discussTypes,
}

